global:
  scrape_interval: 5s # Intervalle de scraping par défaut

scrape_configs:
  - job_name: 'ticket-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'internaute-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'evenement-ms'
    scrape_interval: 5s # Scrape this job every 5 seconds
    static_configs:
      - targets: ['host.docker.internal:8083'] 
    metrics_path: /actuator/prometheus # Update the metrics path
