server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/se-f/tp-tickets-ms.git
          clone-on-start: true
          search-paths: configs
          default-label: main # Specify the branch to pull from
    compatibility-verifier:
      enabled: false